### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by davetang** [theislab/kBET#37]
Hi,

will there be support for sparse matrices with the package? With my data I get the error below, when I try to run `kBet`:

```
Error in La.svd(x, nu, nv) : 
  cannot allocate memory block of size 134217728 Tb
Calls: kBET -> svd -> La.svd
Execution halted
```

Cheers,

Dave

**Comment by alejandro-jimenezsanchez** [comment]
Would be great if this subsampling work around solution for this were added in the instructions in the README.md. I got the same error, thought about it, but it is always good to know the opinion of the developer.

But in addition to this temporal workaround, how much to downsample would it be advisable to still get accurate and reliable results?

**Comment by mbuttner** [comment]
Hi, 
thanks for the comment. I added a few recommendations for subsampling in the README.md file. 
I am terrible at giving general recommendations as subsampling depends on the number of clusters in your data, batch sizes, and number of batches. 
We tested subsampling on PBMC data in the kBET publication (Fig. 5d and Suppl. Fig. 6). When subsampling from 8000 cells to 4000 cells, kBET results where constant, but the rejection rates ( = 1 - acceptance rates in the publication) decreased for smaller subsets. 

I am afraid that I did not record the memory usage of kBET, only the CPU time.

**Comment by alejandro-jimenezsanchez** [comment]
Thanks for addressing my comment. In the README.md file, you say:

> In case of differently sized batches, one should consider stratified sampling in order to keep more samples from smaller batches.

If I understand correctly, would this be solved by selecting the same number of observations per batch? For example, if I have 10 samples and 2 batches, I could subsample the data by taking 100 observations per sample to get a total of 1000 observations. This would ignore the potential different cell numbers per batch.

Is approach correct?

Thank you,
Alejandro

**Comment by mbuttner** [comment]
Dear Alejandro,

I am afraid that I do not quite understand your example. If you have for example 3 batches with 5000, 100 and 1000 observations (cells), then stratified subsampling to 30% dataset size should help you to keep e.g. ~ 90 out of 100 cells from the smallest batch instead of ~ 30 out of 100 cells. 
In general, you have to make sure that you'll keep enough cells per tested group. 

Does that help?

**Comment by alejandro-jimenezsanchez** [comment]
Dear Maren,

I see what you mean. What I thought was to just subsample the same number of observations per sample. Your example is an interesting case because I would then take 100 observations per batch, which may be not good.

Then I think the stratified sampling you suggest would be better. Do you know any R or python function that does that? Or is it something you code on your own.

Thank you,
A
