### ISSUE TITLE
data matrix for kBET evaluation

### ISSUE THREAD

**Issue by phoebee-h** [theislab/kBET#49]
Hi,
I have two questions:
Q1. What kind of data matrix would you suggest for kBET estimation?  
(1) raw counts 
(2) normalized data (log normalized) 
(3) normalized and scaled data
Which one would be proper?

Q2. Thanks for adding the subsampling part! Should I iterate multiple times to get the average results? Or subsampling one time is enough? 

Thanks, 
Phoebe.

**Comment by mbuttner** [comment]
Hi Phoebe,

thanks for your interest! 
To your questions:
Q1: It depends on several factors. We used kBET to compare different batch correction strategies. Personally, I would not look at raw counts to evaluate the batch effect before correction because the differences you'd observe may be driven by cell-specific biases + batch effect; or your evaluation might be dominated by the highest expressed genes. The single-cell community has not picked a favourite normalisation, yet. For full-length protocols (e.g. SMARTseq), we found that TPM normalisation worked well, for droplet-based (3' biased) protocols, such as 10X genomics Chromium, we prefer to normalise with scran. So you might want to evaluate the batch effect with kBET by looking at either normalised or normalised and scaled data. 

Q2: From my experience with subsampling, I'd suggest to perform several subsampling runs to rule out bias introduced by subsampling.
