### ISSUE TITLE
Error when setting nPCs to 2 in batch_sil function

### ISSUE THREAD

**Issue by natalkon** [theislab/kBET#57]
Hi!
I have only PC1 and PC2, so when I try to set nPCs = 2 instead of the default 3
```
pca.data <- prcomp(data, center=TRUE) #compute PCA representation of the data
batch.silhouette <- batch_sil(pca.data, batch, nPCs = 2)
```
I get 
```
Error in if (!all(x == round(x))) stop("'x' must only have integer codes") : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In silhouette(as.numeric(batch), dd) : NAs introduced by coercion
```

I have also tried a different approach:
after PCA dimension reduction (Scanpy) I input the top 40 PCs from the batch-corrected gene expression matrix to the kBET function (matrix: PCs as columns, cells as rows; vector with batch label of each cell). kBET returned an average rejection rate of 1,  thus I tried batch_sil function, but the error remained the same
```
Error in if (!all(x == round(x))) stop("'x' must only have integer codes") : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In silhouette(as.numeric(batch), dd) : NAs introduced by coercion
```

How should I calculate batch.silhouette?
Thanks!

**Comment by mbuttner** [comment]
Hi @natalkon 
can you provide an example where I can reproduce your issue?

**Comment by natalkon** [comment]
Dear @mbuttner , 

Here is an example of a df with 20 cells:

	         Umap1	        Umap2	        batch
cell_1	-3.096921199	30.12484204	donor_1
cell_2	-9.376095629	20.63858649	donor_1
cell_3	-33.63494906	32.87544811	donor_2
cell_4	-33.71569691	33.80216543	donor_1
cell_5	23.96456709	2.549703552	donor_3
cell_6	14.65252946	10.0717695	donor_2
cell_7	12.34270439	19.30039038	donor_1
cell_8	-13.72304483	38.01630477	donor_3
cell_9	12.27810101	21.81083446	donor_1
cell_10	-17.511129	38.59688878	donor_4
cell_11	12.80558118	20.26489032	donor_5
cell_12	-14.08983167	29.7604853	donor_2
cell_13	11.94462239	32.93265876	donor_1
cell_14	-15.92284156	27.99553675	donor_1
cell_15	22.13436047	7.493000427	donor_6
cell_16	5.310249352	17.27575421	donor_7
cell_17	-30.71796877	19.93075148	donor_1
cell_18	25.84398287	1.463291237	donor_1
cell_19	12.91301208	17.99493219	donor_1
cell_20	13.1270876	40.02376185	donor_1

So,

```
library(cluster)
library(kBET)
umap <- mydf[,c('Umap1','Umap2')]
data<-as.matrix(umap)
batch<-as.vector(mydf$batch)
pca.data <- prcomp(data, center=TRUE) #compute PCA representation of the data
batch.silhouette <- batch_sil(pca.data, batch)
# Error in pca.data$x[, seq_len(nPCs)] : subscript out of bounds
batch.silhouette <- batch_sil(pca.data, batch, nPCs = 2, center=TRUE)
#Error in if (!all(x == round(x))) stop("'x' must only have integer codes") : 
#  missing value where TRUE/FALSE needed
#In addition: Warning message:
#In silhouette(as.numeric(batch), dd) : NAs introduced by coercion
```

Could this be a way to calculate
a) kBET
b) silhouette? :

```
umap<- mydf[,c('Umap1','Umap2')]
data<-as.matrix(umap)
batch<-as.vector(mydf$batch)

#a) kBET:
k0=floor(length(table(batch)))
require('FNN')
knn <- get.knn(data, k=k0, algorithm = 'cover_tree')
batch.estimate <- kBET(data, batch, k = k0, knn = knn, do.pca=FALSE, verbose=TRUE)
batch.estimate$summary

#b) silhouette:
indexlookup <- c("donor_1", "donor_2", "donor_3", "donor_4", "donor_5", "donor_6", "donor_7")
batchindex <- match(batch, indexlookup)
memory.limit(size=65000)
dd <- as.matrix(dist(data[,]))
sil <- silhouette(as.numeric(batchindex), dd)
summary(sil)$avg.width
#[1] -0.5185923
```

Thanks!

**Comment by mbuttner** [comment]
Hi @natalkon,

Thank you very much for the example. I was able to reproduce your issue. 
The issue is caused by the `batch` covariate, because it is encoded as string. The silhouette implementation in `kBET` needs a factor or a numeric. Therefore, when converting the `batch` covariate into numeric, it introduces `NA` values.

```
batch.silhouette <- batch_sil(pca.data, as.factor(batch), nPCs = 2)
```
Works just fine and returns `-0.5185921` as result. That seems to correspond with the result of your workaround for the silhouette coefficient. Also, the code for computing kBET in your example looks correct to me. 

However, I have seen that you used UMAP coordinates first to compute a PCA and then a silhouette coefficient. As PCA is a rotation of the original space (here, the UMAP space), you do not loose any info by applying a PCA to UMAP, but I wonder whether using the UMAP coordinates for a silhouette coefficient is meaningful in the first place - I don't think so in general, so please be cautious here. I think that you should rather use the output of the PCA from scanpy to compute the silhouette coefficient directly. When you compute your PCA with scanpy, you might want to have a look at the [scIB package](https://github.com/theislab/scib/) to compute the silhouette coefficient. Here's a quick example (assuming that your data is provided as `anndata` object named `adata`):

```
from scIB import metrics as me
sc.pp.pca(adata)
score = me.silhouette(adata, group_key='batch', embed='X_pca', scale=True)
print(f"score: {score}")
```
 
Similarly, the scIB package has an implementation for kBET:
```
import scIB
from scIB import metrics as me

sc.pp.pca(adata)
sc.pp.neighbors(adata)
score_kBET = me.kBET(adata, batch_key = batch, label_key='cell_type', embed='X_pca', type_ = 'knn')
#use knn as type_ when you have pre-computed the knn-graph, otherwise, the input from embed is used
print(f"score: {score_kBET}")
```
I hope that helps!
