### ISSUE TITLE
how to assess the batch? by rejection rate or silhouette? 

### ISSUE THREAD

**Issue by elva0328** [theislab/kBET#64]
hi, I recently used kbet to assess the batch effect of single-cell dataset. but I'm really confused about how to assess the batch effect according to the result.
1: do you have a cutoff of rejection rate to assess there's a batch or not?
2: I noticed the silhouette score, but confused about the description, it ranged from -1 to 1, from the formula, s(i)>-1, means lower batch, s(i)>1 higher batch; but according to the method part of k-bet paper, the absolute value of s was used to assess absence or presence of batch. so how do we assess the batch by silhouette? 

appreciate your response.

**Comment by mbuttner** [comment]
Hi @elva0328 
thank you for using kBET! 
About your questions: 
1. kBET is a very sensitive method and will almost always report the presence of a batch effect. In general, you can compare the observed rejection rate to the expected rejection rate (which is usually around the sensitivity parameter `alpha= 0.05` by default). We also run a t-test to compare observed and expected rejection rate, but already small different are significant. So we started wondering what is "good enough" in terms of batch effect correction and the answer actually depends on several factors: On the one hand, batch effect correction always goes along with removal of biological signal - you can't have one without the other. On the other hand, you don't want your downstream analysis (e.g. clustering, pseudotime analysis etc.) be affected by the batch effect. In my opinion, one should reduce the batch effect as much as needed to e.g. obtain a good clustering, but not necessarily more because one looses too much of the biological signal then. So there's no clear cutoff for the rejection rate and there's only different degrees of batch effects in the data.
2. Thank you for your question: The silhouette coefficient defines the scaled average distance of a data point in cluster A to the data points in the closest cluster B. When cluster A and B overlap entirely, this average distance is 0. However, negative silhouette coefficients indicate a distorted distribution in both clusters (imagine one cluster as the periphery of a circle and the other cluster as the center - in this artificial case, one obtains negative silhouette scores, but I believe that this setting is "batchy", too.). Therefore, we use the absolute value of the silhouette score.

**Comment by elva0328** [comment]
@mbuttner thanks for your response. really appreciate. 
when I used kbet to evaluate the batch effect,  it seems like that kbet doesn't look good. the batch was removed better from the tsne plot, but the kbet doesn't goes down.
<img width="1104" alt="Screen Shot 2021-09-22 at 4 16 24 PM" src="https://user-images.githubusercontent.com/53468690/134423302-aba232d8-107e-4178-9442-5236e402699c.png">

what season do you think? this is my code, thanks a lot:
`
seuratObj <- sc_before_harmony
DefaultAssay(seuratObj) <- "RNA"
batchLevel <- unique(seuratObj$Batch_ID)
batch <- match(seuratObj$Batch_ID, batchLevel)
sample_size = sum(table(seuratObj$orig.ident))
subset_size <- 0.03 #1
start = 1
end = floor(subset_size*sample_size)
steps = 5
#data = as.matrix(seuratObj@assays$RNA@data) #GetAssayData(object = pbmc, slot = "counts")
#data[1:5, 1:5]
#batch.estimate <- kBET(data,batch,testSize = 1,k0=k0)
totalTibble <- c()
for(k0 in seq(start, end, by = steps)){
  subset_id <- sample.int(n = length(batch),
                          size = floor(subset_size * length(batch)),
                          replace = FALSE)
  batch.estimate <- kBET(seuratObj@reductions$pca@cell.embeddings[subset_id,],
                          batch[subset_id],n_repeat = 100,
                          k0 = k0, plot = FALSE)
  if(is.na(batch.estimate)) {
    next
  }
  tempTibble <- tibble(
    kBET.observed = as.vector(batch.estimate$stats$kBET.observed),
    kBET.expected = as.vector(batch.estimate$stats$kBET.expected),
    kBET.signif   = as.vector(batch.estimate$stats$kBET.signif),
    subset.size = rep(subset_size, length(batch.estimate$stats$kBET.observed)),
    k0 = rep(k0, length(batch.estimate$stats$kBET.observed)))
  totalTibble <- bind_rows(totalTibble, tempTibble)
}

dt = totalTibble
dt$percent = (dt$k0/end)*100
df1 <- dt %>% group_by(percent) %>% summarise(min_ob=quantile(kBET.observed, 0.05), max_ob=quantile(kBET.observed, 0.95), mean_ob=mean(kBET.observed),
                                              min_ep=quantile(kBET.expected, 0.05), max_ep=quantile(kBET.expected, 0.95), mean_ep=mean(kBET.expected))
dt_ob <- df1 %>% transform(low=min_ob, high=max_ob, RejectionRate=mean_ob, type="Observed") %>% select(low, high, RejectionRate, percent, type)
dt_ep <- df1 %>% transform(low=min_ep, high=max_ep, RejectionRate=mean_ep, type="Expected") %>% select(low, high, RejectionRate, percent, type)
df2 <- rbind(dt_ob, dt_ep)
ggplot(df2, aes(x = percent, y=RejectionRate, color=type)) + theme_bw()+
  geom_line() +theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),axis.title.x=element_blank(),axis.title.y=element_blank())+
  geom_ribbon(aes(ymin = low, ymax = high, fill=type), linetype=0, alpha = 0.1)

seuratObj <- scRNA_after_harmony
#bss <- batch_sil_score(seuratObj, seuratObj$Batch_ID, reduction = "harmony") #pca
DefaultAssay(seuratObj) <- "RNA"
batchLevel <- unique(seuratObj$Batch_ID)
batch <- match(seuratObj$Batch_ID, batchLevel)
sample_size = sum(table(seuratObj$orig.ident))
subset_size <- 0.1 #1
start = 1
end = floor(subset_size*sample_size)
steps = 5
#data = as.matrix(seuratObj@assays$RNA@data) #GetAssayData(object = pbmc, slot = "counts")
#data[1:5, 1:5]
#batch.estimate <- kBET(data,batch,testSize = 1,k0=k0)
totalTibble <- c() #length.out
for(k0 in seq(start, end,  by = steps)){
  subset_id <- sample.int(n = length(batch),
                          size = floor(subset_size * length(batch)),
                          replace = FALSE)
  batch.estimate <- kBET(seuratObj@reductions$harmony@cell.embeddings[subset_id,],
                          batch[subset_id],n_repeat = 100,
                          k0 = k0, plot = FALSE)
  if(is.na(batch.estimate)) {
    next
  }
  tempTibble <- tibble(
    kBET.observed = as.vector(batch.estimate$stats$kBET.observed),
    kBET.expected = as.vector(batch.estimate$stats$kBET.expected),
    kBET.signif   = as.vector(batch.estimate$stats$kBET.signif),
    subset.size = rep(subset_size, length(batch.estimate$stats$kBET.observed)),
    k0 = rep(k0, length(batch.estimate$stats$kBET.observed)))
  totalTibble <- bind_rows(totalTibble, tempTibble)
}

dt = totalTibble
dt$percent = (dt$k0/end)*100
df1 <- dt %>% group_by(percent) %>% summarise(min_ob=quantile(kBET.observed, 0.05), max_ob=quantile(kBET.observed, 0.95), mean_ob=mean(kBET.observed),
                                              min_ep=quantile(kBET.expected, 0.05), max_ep=quantile(kBET.expected, 0.95), mean_ep=mean(kBET.expected))
dt_ob <- df1 %>% transform(low=min_ob, high=max_ob, RejectionRate=mean_ob, type="Observed") %>% select(low, high, RejectionRate, percent, type)
dt_ep <- df1 %>% transform(low=min_ep, high=max_ep, RejectionRate=mean_ep, type="Expected") %>% select(low, high, RejectionRate, percent, type)
df2 <- rbind(dt_ob, dt_ep)
ggplot(df2, aes(x = percent, y=RejectionRate, color=type)) + theme_bw()+
  geom_line() +theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),axis.title.x=element_blank(),axis.title.y=element_blank())+
  geom_ribbon(aes(ymin = low, ymax = high, fill=type), linetype=0, alpha = 0.1)

**Comment by mbuttner** [comment]
Closed as completed.
