### ISSUE TITLE
Using kBET for methylation and RNA-Seq data

### ISSUE THREAD

**Issue by mxdeluca** [theislab/kBET#66]
Hi, I came across your method  and thought that it was a great way to query the presence of batch effects in other data types (i.e. methylation arrays and RNA-Seq data). From my understanding of your algorithm, your approach should be fine when applied to other batch effects (e.g. array, plate id, ect...) . What are your thoughts ? Thank you again for this wonderful approach to assess batch effects !

**Comment by mbuttner** [comment]
Hi,
thank you very much for sharing your thoughts! I agree that you may use kBET for other data types, too. The only limit is that you should have a sufficient number of cells (data points) per batch (ideally above 50 cells), so that the heuristic to compute the optimal neighbourhood size works well. There are no other limitations, otherwise.
